sudo: required
services:
  - docker

before_install:
  - docker build -t allenliao0119/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true allenliao0119/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-010438464000"
  bucket_path: "frontend"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main